#!/usr/bin/env python
project_id: 'rare-result-248415'
bucket: 'rare-result-248415-machine-learning'
client_host: 'https://21039ad129525c5a-dot-europe-west2.pipelines.googleusercontent.com'
train: true
model_dir_if_no_train: ''